version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/library_db
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  postgres_data: